### ISSUE TITLE
Debian Bullseye

### ISSUE THREAD

**Issue by wwarne** [brendan-ward/pymgl#7]
This is not actually an  issue.

 I just wanted to share a list of dependencies needed to build pymgl for Debian bullseye in hope it'll help someone.

I use debian because it's used in `python:3.10-slim` docker image which is base image for me right now.

@brendan-ward Thank you a lot for your work on this package. Amazing job.

The steps are the same as for Ubuntu described in [build_wheels.yml ](https://github.com/brendan-ward/pymgl/blob/main/.github/workflows/build_wheels.yml) (mentioned here - https://github.com/brendan-ward/pymgl/issues/6#issuecomment-1258543113)

Build-time dependencies for debian
```
apt-get -y install \
            curl \
            build-essential \
            cmake \
            ccache \
            ninja-build \
            pkg-config \
            libcurl4-openssl-dev \
            libicu-dev \
            libturbojpeg0-dev \
            libpng-dev \
            libprotobuf-dev \
            libuv1-dev \
            libx11-dev \
            libegl-dev \
            libopengl-dev \
            xvfb \
            libjpeg-dev \
            libsqlite3-dev \
            libopengl0 \
            git
```

Runtime dependencies needed to actually use pymgl:
```
apt install --no-install-recommends -y \
       xvfb \
       xauth \
       curl \
       libicu67 \
       libjpeg-turbo-progs \
       libpng16-16 \
       libprotobuf23 \
       libuv1 \
       libx11-6 \
       libegl1 \
       libopengl0
```

**Comment by brendan-ward** [comment]
Thanks @wwarne !

**Comment by brendan-ward** [comment]
This is now added to the [README](https://github.com/brendan-ward/pymgl#debian-bullseye)
